/* A representative mission state with nested scientific data. */
export function buildMissionFixture() {
  return {
    export: { schema: "neuronexus.mission-export.v2", exported_at: "2026-09-30T12:00:00.000Z", sol: 100 },
    selection: {
      mode: "coordinate",
      label: "Curiosity landing",
      latitude_deg: -4.5895,
      longitude_deg: 137.4417,
      selected_feature: {
        feature_name: "Aeolis Mons",
        feature_type: "Mons, montes",
        diameter_km: 96.3,
        approval_status: "Adopted by IAU",
        quadrangle_name: "Aeolis",
        usgs_feature_url: "https://planetarynames.wr.usgs.gov/Feature/14700",
      },
    },
    environment: {
      thermal: {
        source: "NASA THEMIS IR-PBT",
        observations: [
          {
            product_id: "i99827002pbt",
            brightness_temperature_k: 226.78,
            brightness_temperature_c: -46.36,
            latitude_deg: -4.59,
            longitude_deg: 137.44,
            spatial_distance_km: 2.4,
            observation_start: "2024-06-16T00:48:01.020",
            solar_longitude_deg: 275.523,
            local_solar_time_hours: 6.499,
            resolution_m: 100,
            status: "historical_brightness_temperature",
            evidence: { score: 18.5, label: "sparse evidence", observation_count: 1, years: 1 },
          },
          {
            product_id: "i12345002pbt",
            brightness_temperature_k: 198.4,
            brightness_temperature_c: -74.75,
            latitude_deg: -4.61,
            longitude_deg: 137.5,
            spatial_distance_km: 5.1,
            observation_start: "2023-02-01T13:10:00.000",
            solar_longitude_deg: 101.2,
            local_solar_time_hours: 13.2,
            resolution_m: 100,
            status: "historical_brightness_temperature",
          },
        ],
      },
      dust: { opacity: 0.312, height_km: 11.4, scenario: "MY34", status: "modeled" },
      solar: { areocentric_longitude_deg: 275.52 },
      terrain: { elevation_m: -4503, slope_deg: 1.8, aspect_deg: 214.5, roughness_m: 7.4, source: "NASA MOLA MEGDR 128 pixels/degree", pixels_per_degree: 128 },
      site_science: {
        soil: { value: "Basaltic regolith", status: "NASA REFERENCE", source: "NASA", source_url: "https://science.nasa.gov/mars/" },
        minerals: { value: "NOT INGESTED", status: "NOT INGESTED" },
        water: { value: "Evidence required", status: "UNAVAILABLE" },
        bioavailability: { value: "PROXY ONLY", status: "DERIVED" },
        vegetation: { value: "No confirmed native vegetation", status: "NASA REFERENCE" },
        atmosphere: {
          gases: [
            { name: "CO₂", volume_percent: 95.1, status: "NASA REFERENCE", source: "NASA Mars facts" },
            { name: "N₂", volume_percent: 2.59, status: "NASA REFERENCE", source: "NASA Mars facts" },
            { name: "Ar", volume_percent: 1.94, status: "NASA REFERENCE", source: "NASA Mars facts" },
          ],
        },
        notes: 'Context only, "not" a measurement at this coordinate',
      },
      assessment: { assessment_status: "evidence_limited", warnings: ["Sparse thermal evidence"] },
    },
    media: {
      photos: [
        { nasa_id: "PIA16239", title: "Curiosity's view", source: "NASA Image Library", nasa_url: "https://images.nasa.gov/details/PIA16239", date_created: "2012-08-08", rover: "Curiosity", camera: "MASTCAM" },
      ],
    },
    route: {
      id: "route-1",
      name: "Traverse A",
      createdAt: "2026-09-30T11:00:00.000Z",
      coordinates: [
        { latitude_deg: -4.5895, longitude_deg: 137.4417, label: "START" },
        { latitude_deg: -4.62, longitude_deg: 137.41, label: "WP 2" },
        { latitude_deg: -4.72, longitude_deg: 137.38, label: "DESTINATION" },
      ],
      metrics: {
        distance_km: 9.2174,
        displacement_km: 8.55,
        estimated_eva_hours: 4.187,
        eva_pace_kmh: 2.5,
        mean_slope_deg: 2.142,
        max_slope_deg: 7.543,
        mean_roughness_m: 4.1,
        max_roughness_m: 12.7,
        elevation_min_m: -4520,
        elevation_max_m: -4402,
        elevation_gain_m: 118,
        elevation_loss_m: 61,
        terrain_burden_score: 16.69,
        terrain_risk_proxy: 32.95,
        operational_burden_score: 44.48,
        science_opportunity_score: 50,
        science_evidence_count: 1,
        data_support_score: 100,
        objective_score: 1.0159,
        route_generation_time_ms: 90.5,
      },
      warnings: ["One or more waypoints exceed 5° local slope"],
      waypoint_analysis: [
        { label: "START", latitude_deg: -4.5895, longitude_deg: 137.4417, status: "available", elevation_m: -4503, slope_deg: 1.8, aspect_deg: 214.5, roughness_m: 7.4, local_elevation_min_m: -4510, local_elevation_max_m: -4496 },
        { label: "DESTINATION", latitude_deg: -4.72, longitude_deg: 137.38, status: "available", elevation_m: -4441, slope_deg: 3.2, aspect_deg: 98.1, roughness_m: 9.9, local_elevation_min_m: -4455, local_elevation_max_m: -4430 },
      ],
      generation_method: "Deterministic Dijkstra over MOLA 128 ppd",
      eva: { pace_kmh: 2.5, ascent_allowance_m_per_h: 600 },
    },
    route_candidates: {
      selected_id: "cand-balanced",
      pareto: { non_dominated_ids: ["cand-balanced", "cand-low-eva"] },
      candidates: [
        {
          id: "cand-balanced",
          name: "Balanced",
          objective_weights: { eva: 25, terrain: 25, science: 25, operational: 25 },
          generation_method: "Deterministic Dijkstra, RDP simplification",
          algorithm_version: "neuronexus-route-mo 1.0.0",
          pareto_label: "PARETO / NON-DOMINATED",
          coordinates: [
            { latitude_deg: -4.5895, longitude_deg: 137.4417, label: "START" },
            { latitude_deg: -4.72, longitude_deg: 137.38, label: "DESTINATION" },
          ],
          metrics: { distance_km: 9.2174, estimated_eva_hours: 4.187, terrain_risk_proxy: 32.95, science_opportunity_score: 50, science_evidence_count: 1, route_generation_time_ms: 90.5 },
          uncertainties: ["Planning grid cell ~463 m", "SCIENCE EVIDENCE UNAVAILABLE beyond catalogued items"],
          ai_explanation: "Balanced trade-off, per the weighted sum.",
          provenance: { terrain: "NASA MOLA MEGDR 128 ppd", eva_pace_kmh: 2.5 },
        },
        {
          id: "cand-low-eva",
          name: "Low EVA",
          objective_weights: { eva: 100, terrain: 0, science: 0, operational: 0 },
          pareto_label: "PARETO / NON-DOMINATED",
          coordinates: [
            { latitude_deg: -4.5895, longitude_deg: 137.4417, label: "START" },
            { latitude_deg: -4.72, longitude_deg: 137.38, label: "DESTINATION" },
          ],
          metrics: { distance_km: 8.9, estimated_eva_hours: 3.98, terrain_risk_proxy: 35.5, science_opportunity_score: null, science_evidence_count: null },
          uncertainties: ["SCIENCE EVIDENCE UNAVAILABLE for this planning window"],
        },
      ],
      methodology: { scalarisation: "weighted sum of normalised objectives", objective_optima: { eva: 3.5, terrain: 1.2, science: 2.0, operational: 4.4 } },
    },
    saved_routes: [{ id: "route-1", name: "Traverse A", metrics: { distance_km: 9.2174 } }],
    safe_havens: [{ id: "haven-1", name: "Safe Haven 1, north", latitude_deg: -4.6, longitude_deg: 137.44, createdAt: "2026-09-29T10:00:00.000Z" }],
    custom_places: [{ id: "place-1", name: "Outcrop\nsample", latitude_deg: -4.63, longitude_deg: 137.42 }],
    mission_console: {
      mission: { id: { value: "NN-MARS-01", status: "CONFIGURABLE" }, sol: { value: 100, status: "PROJECT DATA" } },
      eva: { estimated_eva_hours: { value: 4.187, status: "DERIVED" } },
      resources: { atmosphere: [{ name: "CO₂", volume_percent: 95.1, status: "NASA REFERENCE" }] },
    },
    orbital_tracking: {
      status: "live",
      retrieved_at: "2026-09-30T11:59:00.000Z",
      source: { name: "NASA/JPL SSD Close-Approach Data (CAD) API" },
      objects: [
        { designation: "2015 MY53", object: "(2015 MY53)", close_approach_tdb: "2027-May-18 23:06", distance_au: 0.0038, distance_km: 568472.9, distance_min_au: 0.0038, distance_max_au: 0.0527, relative_velocity_km_s: 10.31, time_sigma_raw: "5_04:33", tracking_status: "HIGH-PRIORITY MONITORING", sbdb_url: "https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2015%20MY53" },
      ],
    },
    mission_notes: { todo: "Check ramp, then\nsample", checklist: [{ id: "check-1", text: "Verify suit", done: false }] },
    provenance: { mola: { source: "NASA MOLA MEGDR", status: "NASA OBSERVED" }, gemini: { source: "Google Gemini", status: "AI INTERPRETATION" } },
    software: { app_version: "2.0.0", route_engine: "neuronexus-route-mo 1.0.0" },
  };
}
