import { useMemo } from "react";

import { CANDIDATE_COLOURS, OBJECTIVES, OBJECTIVE_PRESETS as PRESETS, matchPreset, rebalanceWeights } from "../../utils/routeObjectives";

/*
 * AI ROUTE DESIGN workspace.
 *
 * The routes themselves are NOT generated by a language model. The backend
 * runs a deterministic Dijkstra search over a bounded NASA MOLA 128 ppd
 * window and computes every metric. Gemini is asked only to interpret the
 * structured result, and it may never change a number.
 */

function format(value, digits = 2, suffix = "") {
  if (value === null || value === undefined || Number.isNaN(Number(value))) {
    return "UNAVAILABLE";
  }
  return `${Number(value).toFixed(digits)}${suffix}`;
}

function CandidateCard({ candidate, colour, active, onSelect, onApply, analysis }) {
  const metrics = candidate.metrics ?? {};
  const weights = candidate.objective_weights ?? candidate.scoring_weights ?? {};
  return (
    <article className={`ai-candidate${active ? " active" : ""}`} style={{ borderColor: active ? colour : undefined }}>
      <header
        onClick={() => onSelect(candidate.id)}
        role="button"
        tabIndex={0}
        onKeyDown={(event) => event.key === "Enter" && onSelect(candidate.id)}
      >
        <span className="ai-candidate-swatch" style={{ background: colour }} />
        <div>
          <strong>{candidate.name}</strong>
          <small>{candidate.pareto_label}</small>
        </div>
        <span className="ai-candidate-score">{format(metrics.objective_score, 3)}</span>
      </header>

      <div className="ai-candidate-metrics">
        <div>
          <span>Distance</span>
          <strong>{format(metrics.distance_km, 2, " km")}</strong>
        </div>
        <div>
          <span>Est. EVA</span>
          <strong>{format(metrics.estimated_eva_hours, 2, " h")}</strong>
        </div>
        <div>
          <span>Terrain burden</span>
          <strong>{format(metrics.terrain_burden_score, 1)}</strong>
        </div>
        <div>
          <span>Risk proxy</span>
          <strong>{format(metrics.terrain_risk_proxy, 1)}</strong>
        </div>
        <div>
          <span>Mean slope</span>
          <strong>{format(metrics.mean_slope_deg, 2, "°")}</strong>
        </div>
        <div>
          <span>Max slope</span>
          <strong>{format(metrics.max_slope_deg, 2, "°")}</strong>
        </div>
        <div>
          <span>Elev. gain</span>
          <strong>{format(metrics.elevation_gain_m, 0, " m")}</strong>
        </div>
        <div>
          <span>Science</span>
          <strong>
            {metrics.science_opportunity_score == null
              ? "EVIDENCE UNAVAILABLE"
              : `${format(metrics.science_opportunity_score, 0)} · ${metrics.science_evidence_count} item(s)`}
          </strong>
        </div>
        <div>
          <span>Ops burden</span>
          <strong>{format(metrics.operational_burden_score, 1)}</strong>
        </div>
        <div>
          <span>Data support</span>
          <strong>{format(metrics.data_support_score, 0, "%")}</strong>
        </div>
      </div>

      <div className="ai-candidate-weights">
        {OBJECTIVES.map(([key, label]) => (
          <span key={key}>
            {label} {weights[key] ?? 0}%
          </span>
        ))}
      </div>

      <p className="ai-candidate-basis">{candidate.objective_basis}</p>
      <p className="ai-candidate-method">{candidate.generation_method}</p>

      {analysis?.summaryFor === candidate.id && analysis.text && <p className="ai-candidate-ai">{analysis.text}</p>}

      <details>
        <summary>Uncertainties ({candidate.uncertainties?.length ?? 0})</summary>
        <ul>
          {(candidate.uncertainties ?? []).map((item) => (
            <li key={item}>{item}</li>
          ))}
        </ul>
        {metrics.science_evidence?.length > 0 && (
          <>
            <strong>Science evidence engaged</strong>
            <ul>
              {metrics.science_evidence.slice(0, 8).map((item) => (
                <li key={item.id}>
                  {item.url ? (
                    <a href={item.url} target="_blank" rel="noreferrer">
                      {item.name}
                    </a>
                  ) : (
                    item.name
                  )}{" "}
                  — {item.source} ({item.status}), {format(item.min_distance_km, 2, " km")}
                </li>
              ))}
            </ul>
          </>
        )}
      </details>

      <div className="ai-candidate-actions">
        <button type="button" onClick={() => onSelect(candidate.id)}>
          {active ? "HIGHLIGHTED" : "HIGHLIGHT"}
        </button>
        <button type="button" className="primary" onClick={() => onApply(candidate)}>
          APPLY ROUTE
        </button>
      </div>
    </article>
  );
}

export default function AiRouteDesigner({
  open,
  onClose,
  start,
  destination,
  selectedLocation,
  safeHavens = [],
  result,
  loading,
  error,
  analysis,
  analysisLoading,
  aiStatus,
  selectedCandidateId,
  weights,
  evaPace,
  ascentAllowance,
  includeScience,
  onSetStart,
  onSetDestination,
  onWeightsChange,
  onEvaPaceChange,
  onAscentAllowanceChange,
  onIncludeScienceChange,
  onGenerate,
  onSelectCandidate,
  onApplyCandidate,
  onRequestAnalysis,
}) {
  const activePreset = useMemo(() => matchPreset(weights), [weights]);

  const total = useMemo(() => OBJECTIVES.reduce((sum, [key]) => sum + (Number(weights[key]) || 0), 0), [weights]);
  const candidates = result?.candidates ?? [];

  if (!open) {
    return null;
  }

  return (
    <div className="ai-designer-backdrop" role="dialog" aria-label="AI route design workspace">
      <section className="ai-designer">
        <header className="ai-designer-head">
          <div>
            <span className="eyebrow">ROUTE DESIGN / DETERMINISTIC ENGINE + AI INTERPRETATION</span>
            <h2>AI ROUTE DESIGN</h2>
            <small>
              Candidates are generated by deterministic multi-objective search over NASA MOLA 128 ppd terrain. A language model never produces route
              geometry.
            </small>
          </div>
          <button type="button" className="ai-close" onClick={onClose} aria-label="Close route designer">
            ×
          </button>
        </header>

        <div className="ai-designer-body">
          <aside className="ai-designer-controls">
            <div className="ai-field">
              <span>START</span>
              <strong>{start ? `${Number(start.latitude_deg).toFixed(4)}°, ${Number(start.longitude_deg).toFixed(4)}°E` : "NOT SET"}</strong>
              <small>{start?.label ?? ""}</small>
              <button type="button" disabled={!selectedLocation} onClick={onSetStart}>
                USE SELECTED SITE
              </button>
            </div>

            <div className="ai-field">
              <span>DESTINATION</span>
              <strong>
                {destination ? `${Number(destination.latitude_deg).toFixed(4)}°, ${Number(destination.longitude_deg).toFixed(4)}°E` : "NOT SET"}
              </strong>
              <small>{destination?.label ?? ""}</small>
              <button type="button" disabled={!selectedLocation} onClick={onSetDestination}>
                USE SELECTED SITE
              </button>
            </div>

            <div className="ai-presets">
              {Object.keys(PRESETS).map((key) => (
                <button key={key} type="button" className={activePreset === key ? "active" : ""} onClick={() => onWeightsChange({ ...PRESETS[key] })}>
                  {key.replaceAll("_", " ")}
                </button>
              ))}
            </div>

            <div className="ai-weights">
              <div className="ai-weights-head">
                <span>MISSION OBJECTIVES</span>
                <strong className={total === 100 ? "ok" : "warn"}>TOTAL {total}%</strong>
              </div>
              {OBJECTIVES.map(([key, label]) => (
                <label key={key}>
                  <span>{label}</span>
                  <input
                    type="range"
                    min="0"
                    max="100"
                    step="1"
                    value={weights[key] ?? 0}
                    onChange={(event) => onWeightsChange(rebalanceWeights(weights, key, event.target.value))}
                  />
                  <strong>{weights[key] ?? 0}%</strong>
                </label>
              ))}
              <small>
                Weights always total 100%. The optimisation is a weighted sum of objectives normalised by each objective's own optimum on the same
                planning grid.
              </small>
            </div>

            <div className="ai-numeric">
              <label>
                <span>EVA PACE</span>
                <input
                  type="number"
                  min="0.2"
                  max="10"
                  step="0.1"
                  value={evaPace}
                  onChange={(event) => onEvaPaceChange(Number(event.target.value))}
                />
                <small>km/h</small>
              </label>
              <label>
                <span>ASCENT ALLOWANCE</span>
                <input
                  type="number"
                  min="0"
                  max="5000"
                  step="50"
                  value={ascentAllowance}
                  onChange={(event) => onAscentAllowanceChange(Number(event.target.value))}
                />
                <small>m/h</small>
              </label>
              <label className="ai-check">
                <input type="checkbox" checked={includeScience} onChange={(event) => onIncludeScienceChange(event.target.checked)} />
                <span>Use ingested science evidence (USGS/IAU + THEMIS)</span>
              </label>
            </div>

            <button type="button" className="ai-generate" disabled={!start || !destination || loading} onClick={onGenerate}>
              {loading ? "GENERATING…" : "GENERATE ROUTES"}
            </button>

            <button
              type="button"
              className="ai-analyse"
              disabled={!candidates.length || analysisLoading}
              onClick={onRequestAnalysis}
              title={aiStatus?.configured ? `Gemini model: ${aiStatus.model}` : "GEMINI_API_KEY is not configured on the server"}
            >
              {analysisLoading ? "ASKING GEMINI…" : "AI TRADE-OFF ANALYSIS"}
            </button>

            {error && <div className="ai-error">{error}</div>}
            {safeHavens.length > 0 && <small className="ai-note">{safeHavens.length} Safe Haven(s) inform the operational-burden objective.</small>}
          </aside>

          <div className="ai-designer-results">
            {result && (
              <div className="ai-run-summary">
                <div>
                  <span>WINDOW</span>
                  <strong>
                    {format(result.window?.width_km, 1, " × ")}
                    {format(result.window?.height_km, 1, " km")}
                  </strong>
                </div>
                <div>
                  <span>PLANNING GRID</span>
                  <strong>
                    {result.window?.planning_rows}×{result.window?.planning_cols} @ {format(result.window?.planning_cell_km, 3, " km")}
                  </strong>
                </div>
                <div>
                  <span>TERRAIN</span>
                  <strong>{result.window?.terrain_source}</strong>
                </div>
                <div>
                  <span>GENERATION</span>
                  <strong>{format(result.timing_ms?.total_ms, 0, " ms")}</strong>
                </div>
                <div>
                  <span>PARETO SET</span>
                  <strong>
                    {result.pareto?.non_dominated_ids?.length ?? 0} / {candidates.length}
                  </strong>
                </div>
              </div>
            )}

            {analysis?.status === "ok" && analysis.analysis && (
              <div className="ai-analysis">
                <header>
                  <span>AI INTERPRETATION · {analysis.model}</span>
                  <strong>confidence: {analysis.analysis.confidence}</strong>
                </header>
                <p>{analysis.analysis.summary}</p>
                <p className="ai-analysis-basis">
                  <strong>Basis:</strong> {analysis.analysis.recommendation_basis}
                </p>
                <ul>
                  {(analysis.analysis.tradeoffs ?? []).map((item) => (
                    <li key={`${item.candidate}-${item.advantage}`}>
                      <strong>{item.candidate}</strong> — {item.advantage} · cost: {item.cost} <em>({item.metric_basis})</em>
                    </li>
                  ))}
                </ul>
                {(analysis.analysis.uncertainties ?? []).length > 0 && (
                  <details>
                    <summary>Uncertainties and evidence</summary>
                    <ul>
                      {analysis.analysis.uncertainties.map((item) => (
                        <li key={item}>{item}</li>
                      ))}
                    </ul>
                    <ul>
                      {(analysis.analysis.evidence ?? []).map((item, index) => (
                        <li key={`${item.claim}-${index}`}>
                          [{item.evidence_class}] {item.claim}: {item.value} — {item.source}
                        </li>
                      ))}
                    </ul>
                  </details>
                )}
                <small>AI INTERPRETATION of deterministic results. Numbers remain those computed by the engine.</small>
              </div>
            )}

            {analysis && analysis.status !== "ok" && (
              <div className="ai-error">GEMINI UNAVAILABLE — {analysis.reason ?? analysis.error}. Deterministic candidates above are unaffected.</div>
            )}

            <div className="ai-candidate-grid">
              {candidates.map((candidate, index) => (
                <CandidateCard
                  key={candidate.id}
                  candidate={candidate}
                  colour={CANDIDATE_COLOURS[index % CANDIDATE_COLOURS.length]}
                  active={candidate.id === selectedCandidateId}
                  onSelect={onSelectCandidate}
                  onApply={onApplyCandidate}
                  analysis={null}
                />
              ))}
              {!candidates.length && !loading && (
                <div className="ai-empty">
                  Set a start and a destination, choose objectives, then generate candidates. All generated candidates stay visible together on the
                  coloured map.
                </div>
              )}
            </div>

            {result?.methodology && (
              <details className="ai-methodology">
                <summary>Scoring methodology, terrain-risk proxy and limitations</summary>
                <p>{result.methodology.scalarisation}</p>
                <p>
                  <strong>{result.methodology.name}:</strong> {result.methodology.terrain_risk_proxy}
                </p>
                <p>
                  <strong>Terrain burden:</strong> {result.methodology.terrain_burden_score}
                </p>
                <p>
                  <strong>Estimated EVA time:</strong> {result.methodology.estimated_eva_time}
                </p>
                <p>
                  <strong>Science:</strong> {result.methodology.science_opportunity_score}
                </p>
                <p>
                  <strong>Pareto:</strong> {result.methodology.pareto}
                </p>
                <ul>
                  {(result.methodology.limitations ?? []).map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
                <p className="ai-safety">{result.safety_notice}</p>
              </details>
            )}
          </div>
        </div>
      </section>
    </div>
  );
}
